title: The Wblzoids
subtitle: GameDev
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Articles
      url: /blog
    - text: Courses
      url: /courses
#    - text: Gallery
#      url: /gallery
#    - text: About
#      url: /about
#    - text: Shop
#      url : /shop
#    - text: Contact Me
#      url : /contact
#    - text: Styleguide
#      url: /styleguide
#    - text: Get Started
#      url: /get-started

# Edit these details

author_logo: profile.png
megaphone: megaphone.png
author: blnglishPlease
author_bio: My way to far far away...
author_email: "thewblzoids@gmail.com"
author_location: Russia
#author_website_url: "vk.com/joraiznewjersi"
typewrite-text: this site can make you convert to islam...

author_work_experiences:
            - company_name:
              company_logo:
              company_url:
              designation:
              description:
              visibility:

author_education_details:
              - college_logo:
                college_name:
                college_url:
                college_degree:
                description:
                visibility:

author_project_details:
              - project_thumbnail:
                project_title:
                project_description:
                project_url:
                visibility:

# social links
#twitter_username: johndoe
github_username:  TheWblzoids
#facebook_username: johndoe
#linkedin_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url:

# formspree (contact form)
formspree_email:

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: false
show_author_bio: false

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
