---
title: The Wblzoids
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: gallery
  values:
    permalink: "/:path/:basename:output_ext"
subtitle: GameDev
description: 
url: 
baseurl: 
urls:
- text: Articles
  url: "/blog"
- text: Courses
  url: "/courses"
author_logo: profile.png
megaphone: megaphone.png
author: blnglishPlease
author_bio: My way to far far away...
author_email: thewblzoids@gmail.com
author_location: Russia
typewrite-text: this site can make you convert to islam...
author_work_experiences:
- company_name: 
  company_logo: 
  company_url: 
  designation: 
  description: 
  visibility: 
author_education_details:
- college_logo: 
  college_name: 
  college_url: 
  college_degree: 
  description: 
  visibility: 
author_project_details:
- project_thumbnail: 
  project_title: 
  project_description: 
  project_url: 
  visibility: 
github_username: TheWblzoids
mailchimp_form_url: 
formspree_email: 
markdown: kramdown
highlighter: rouge
permalink: pretty
google_analytics: UA-46783401-10
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: false
show_author_bio: false
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts
  nodes_to_index: article
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-algolia
- jekyll-menus
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
destination: "./build"
